[project]
name = 'btc-tx-enabled-nft'
description = 'A Clarity smart contract that allows you to mint an NFT based on a bitcoin transaction.'
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.clarity-bitcoin-lib-v5'

[contracts.btc-tx-enabled-nft]
path = 'contracts/btc-tx-enabled-nft.clar'
clarity_version = 3
epoch = 3.0
